# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola//setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/additional

BOARD_PLAT_PRIVATE_SEPOLICY_DIRS += \
    vendor/motorola/MotoSignatureApp/sepolicy/private

PRODUCT_COPY_FILES += \
    vendor/motorola/additional/proprietary/product/etc/default-permissions/default-permission-com.motorola.timeweatherwidget.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/default-permissions/default-permission-com.motorola.timeweatherwidget.xml \
    vendor/motorola/additional/proprietary/product/etc/default-permissions/default-permissions-com.motorola.gamemode.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/default-permissions/default-permissions-com.motorola.gamemode.xml \
    vendor/motorola/additional/proprietary/product/etc/permissions/com.motorola.gamemode.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.gamemode.xml \
    vendor/motorola/additional/proprietary/product/etc/permissions/com.motorola.timeweatherwidget.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.timeweatherwidget.xml \
    vendor/motorola/additional/proprietary/product/etc/permissions/privapp-permissions-com.motorola.gamemode.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-com.motorola.gamemode.xml \
    vendor/motorola/additional/proprietary/product/etc/sysconfig/hiddenapi-whitelist-com.motorola.gamemode.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/hiddenapi-whitelist-com.motorola.gamemode.xml \
    vendor/motorola/additional/proprietary/product/etc/sysconfig/hiddenapi-whitelist-com.motorola.timeweatherwidget.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/hiddenapi-whitelist-com.motorola.timeweatherwidget.xml \
    vendor/motorola/additional/proprietary/product/etc/sysconfig/shortcut-com.motorola.gamemode.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/shortcut-com.motorola.gamemode.xml \
    vendor/motorola/additional/proprietary/system/bin/dropboxhelper:$(TARGET_COPY_OUT_SYSTEM)/bin/dropboxhelper \
    vendor/motorola/additional/proprietary/system/etc/permissions/com.motorola.frameworks.core.addon.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.frameworks.core.addon.xml \
    vendor/motorola/additional/proprietary/system/etc/permissions/com.motorola.motosignature.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.motosignature.xml \
    vendor/motorola/additional/proprietary/system/etc/permissions/moto-checkin.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/moto-checkin.xml \
    vendor/motorola/additional/proprietary/system/etc/permissions/moto-core_services.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/moto-core_services.xml \
    vendor/motorola/additional/proprietary/system/etc/permissions/moto-settings.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/moto-settings.xml \
    vendor/motorola/additional/proprietary/system_ext/bin/motsettings:$(TARGET_COPY_OUT_SYSTEM_EXT)/bin/motsettings \
    vendor/motorola/additional/proprietary/system_ext/etc/permissions/afw-com.motorola.livewallpaper.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/afw-com.motorola.livewallpaper.xml \
    vendor/motorola/additional/proprietary/system_ext/etc/permissions/com.motorola.game_moment.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.motorola.game_moment.xml \
    vendor/motorola/additional/proprietary/system_ext/etc/permissions/feature-com.motorola.motolivewallpaper3.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/feature-com.motorola.motolivewallpaper3.xml \
    vendor/motorola/additional/proprietary/system_ext/etc/permissions/privapp-permissions-com.motorola.livewallpaper.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-com.motorola.livewallpaper.xml

PRODUCT_PACKAGES += \
    MotoSignature2App \
    MotoSignatureApp \
    TimeWeather \
    GameMode \
    MotoLiveWallpaper3 \
    MotorolaSettingsProvider \
    com.motorola.android.dropboxhelper \
    com.motorola.frameworks.core.addon \
    com.motorola.motosignature \
    moto-checkin \
    moto-core_services \
    moto-settings
