# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/additional/setup-makefiles.sh

SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += \
    vendor/motorola/additional/sepolicy/private
